CREATE TABLE item_category(
   -> id int(11) PRIMARY KEY AUTO_INCREMENT,
   -> category_name varchar(256) NOT NULL);

   INSERT INTO item_category (category_name)VALUES('デッキ');

    INSERT INTO item_category (category_name)VALUES('デッキテープ');

     INSERT INTO item_category (category_name)VALUES('トラック');

      INSERT INTO item_category (category_name)VALUES('ウィール');

       INSERT INTO item_category (category_name)VALUES('ビス');

        INSERT INTO item_category (category_name)VALUES('ベアリング');
